# Esta configuración la he sacado de: https://metallb.universe.tf/configuration/#layer-2-configuration
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.101-192.168.99.102
  # En la línea de arriba se pondría el rango de ips a reservar para el loadBalancer